version: '3.4'
services:

  zookeeper:
    extends:
      file: docker-compose-base.yml
      service: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - ./test_data/zookeeper/data:/test_data
      - ./test_data/zookeeper/datalog:/test_datalog

  broker:
    extends:
      file: docker-compose-base.yml
      service: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - ./test_data/broker/data:/var/lib/broker/test_data

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: broker:29092
    depends_on:
      - broker

  clickhouse-node1:
    extends:
      file: docker-compose-base.yml
      service: clickhouse-node1
    ports:
      - "8123:8123"
    depends_on:
      - zookeeper
      - broker

  clickhouse-node2:
    extends:
      file: docker-compose-base.yml
      service: clickhouse-node2
    depends_on:
      - zookeeper
      - broker

  mongo:
    image: mongo:6.0.1
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo:/data/db
    env_file:
      - ./.env
    ports:
      - "6000:27017"

  mongo-express:
    image: mongo-express:latest
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
    ports:
      - "8081:8081"

  fastapi:
    image: fastapi-image
    extends:
      file: docker-compose-base.yml
      service: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - broker

#  e2e-tests:
#     image: fastapi-image
#     entrypoint: >
#       sh -c "pytest tests/src/e2e"
#     env_file:
#       - ./.env
#     depends_on:
#       - broker
#       - clickhouse-node1
#       - fastapi

volumes:
  mongo:
