@startuml

!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!includeurl ICONURL/common.puml
!include <C4/C4_Container>
!include <C4/C4_Context>
!include ICONURL/devicons/postgresql.puml
!includeurl ICONURL/material/email.puml
!includeurl ICONURL/material/queue.puml
!includeurl ICONURL/material/schedule.puml
skinparam backgroundColor MOTIVATION

title [C2]: TO BE

HIDE_STEREOTYPE()
SHOW_PERSON_OUTLINE()

Person(Marketer, "Маркетолог", "Отправляет коммуникации")

System_Boundary(services, "Other services") {
    Container(auth_service, "Auth Service", "Сервис аутентификации")
    Container(ugc_service, "UGC Service", "Сервис для отслеживания активности пользователя")
}
System_Boundary(notifications, "Нотификации") {
    Container(notifications_service, "Notifications API", "Сервис для отправки коммуникаций пользователям")
    Container(templates_service, "Templates Service", "CRUD шаблонов и рендер")
    Container(notifications_admin_panel, "Notifications Admin Panel", "Админ панель для регистрации и отправки коммуникаций")
    Container(notifications_enricher_consumer, "Консьюмер-обогатитель", "Готовит и обогащает коммуникации для отправки")
    Container(regular_daemon, "Шедулер регулярных отправок", "Добавляет коммуникации в очередь для отправки")
    Container(email_consumer, "Воркер по отправке коммуникаций", "Заполняет шаблон и отправляет Email провайдеру")
    System_Boundary(rabbitmq, "RabbitMQ") {
        Container(process_queue, "Очередь для обработки", "notification_id, campaing_id")
        Container(send_queue, "Очередь для отправки", "notification_id, campaing_id")
    }
    Container(notificationsDB, "Notifications DB", "БД коммуникаций", $sprite="postgresql")
    Container(templatesDB, "Templates DB", "БД шаблонов", $sprite="postgresql")
}
Container(email_provider, "Email provider", "Внешний сервис по отправке имейлов", $sprite="email")

[Marketer] --> [notifications_admin_panel]
Rel(notifications_admin_panel, notifications_service, "Разовая отправка коммуникаций")
Rel(notifications_admin_panel, templates_service, "CRUD шаблона")
Rel(templates_service, templatesDB, "Шаблоны")
Rel(services, notifications_service, "Запросы на отправку коммуникаций")
Rel(notifications_service, process_queue, "Сообщение в очередь на обработку с notification_id")
Rel(process_queue, notifications_enricher_consumer, "Шаблон")
Rel(notificationsDB, notifications_enricher_consumer, "Шаблон коммуникации")
Rel(notifications_enricher_consumer, send_queue, "Сообщения с типом сразу")
Rel(notifications_enricher_consumer, notificationsDB, "Обогащенные данные для коммуникации")
Rel(notificationsDB, regular_daemon, "Коммуникации, отфильтрованные по таймзоне")
Rel(regular_daemon, send_queue, "Готовые к отправке")
Rel(send_queue, email_consumer, "Сообщения для отправки")
Rel(notificationsDB, email_consumer, "Модель коммуникации")
Rel(templates_service, email_consumer, "Отрендеренный имейл")
Rel(email_consumer, email_provider, "Данные для отправки")
Rel(email_consumer, notificationsDB, "Статусы отправки")

@enduml